#if UNITY_2019_1
using UnityEngine;
using UnityEditor;
using System;

namespace HananokiEditor {
	public static partial class EditorIcon {

		// lightskin and darkskin
		public static Texture2D _popup                            => Icon.GetOrLoadFromBuiltin( IconPath( "_popup" ) ); // _Popup
		public static Texture2D aboutwindow_mainheader            => Icon.GetOrLoadFromBuiltin( IconPath( "aboutwindow.mainheader" ) ); // aboutwindow.mainheader
		public static Texture2D ageialogo                         => Icon.GetOrLoadFromBuiltin( IconPath( "ageialogo" ) ); // ageialogo
		public static Texture2D alphabeticalsorting               => Icon.GetOrLoadFromBuiltin( IconPath( "alphabeticalsorting" ) ); // AlphabeticalSorting
		public static Texture2D animation_addevent                => Icon.GetOrLoadFromBuiltin( IconPath( "animation.addevent" ) ); // Animation.AddEvent
		public static Texture2D animation_addkeyframe             => Icon.GetOrLoadFromBuiltin( IconPath( "animation.addkeyframe" ) ); // Animation.AddKeyframe
		public static Texture2D animation_eventmarker             => Icon.GetOrLoadFromBuiltin( IconPath( "animation.eventmarker" ) ); // Animation.EventMarker
		public static Texture2D animation_firstkey                => Icon.GetOrLoadFromBuiltin( IconPath( "animation.firstkey" ) ); // Animation.FirstKey
		public static Texture2D animation_lastkey                 => Icon.GetOrLoadFromBuiltin( IconPath( "animation.lastkey" ) ); // Animation.LastKey
		public static Texture2D animation_nextkey                 => Icon.GetOrLoadFromBuiltin( IconPath( "animation.nextkey" ) ); // Animation.NextKey
		public static Texture2D animation_play                    => Icon.GetOrLoadFromBuiltin( IconPath( "animation.play" ) ); // Animation.Play
		public static Texture2D animation_prevkey                 => Icon.GetOrLoadFromBuiltin( IconPath( "animation.prevkey" ) ); // Animation.PrevKey
		public static Texture2D animation_record                  => Icon.GetOrLoadFromBuiltin( IconPath( "animation.record" ) ); // Animation.Record
		public static Texture2D animation_sequencerlink           => Icon.GetOrLoadFromBuiltin( IconPath( "animation.sequencerlink" ) ); // Animation.SequencerLink
		public static Texture2D animationanimated                 => Icon.GetOrLoadFromBuiltin( IconPath( "animationanimated" ) ); // animationanimated
		public static Texture2D animationkeyframe                 => Icon.GetOrLoadFromBuiltin( IconPath( "animationkeyframe" ) ); // animationkeyframe
		public static Texture2D animationnocurve                  => Icon.GetOrLoadFromBuiltin( IconPath( "animationnocurve" ) ); // animationnocurve
		public static Texture2D animationvisibilitytoggleoff      => Icon.GetOrLoadFromBuiltin( IconPath( "animationvisibilitytoggleoff" ) ); // animationvisibilitytoggleoff
		public static Texture2D animationvisibilitytoggleon       => Icon.GetOrLoadFromBuiltin( IconPath( "animationvisibilitytoggleon" ) ); // animationvisibilitytoggleon
		public static Texture2D animationwrapmodemenu             => Icon.GetOrLoadFromBuiltin( IconPath( "animationwrapmodemenu" ) ); // AnimationWrapModeMenu
		public static Texture2D assemblylock                      => Icon.GetOrLoadFromBuiltin( IconPath( "assemblylock" ) ); // AssemblyLock
		public static Texture2D asset_store                       => Icon.GetOrLoadFromBuiltin( IconPath( "asset store" ) ); // Asset Store
		public static Texture2D audio_mixer                       => Icon.GetOrLoadFromBuiltin( IconPath( "audio mixer" ) ); // Audio Mixer
		public static Texture2D avatarcompass                     => Icon.GetOrLoadFromBuiltin( IconPath( "avatarcompass" ) ); // AvatarCompass
		public static Texture2D avatarpivot                       => Icon.GetOrLoadFromBuiltin( IconPath( "avatarpivot" ) ); // AvatarPivot
		public static Texture2D back                              => Icon.GetOrLoadFromBuiltin( IconPath( "back" ) ); // back
		public static Texture2D back_2x                           => Icon.GetOrLoadFromBuiltin( IconPath( "back@2x" ) ); // back@2x
		public static Texture2D beginbutton_on                    => Icon.GetOrLoadFromBuiltin( IconPath( "beginbutton-on" ) ); // beginButton-On
		public static Texture2D beginbutton                       => Icon.GetOrLoadFromBuiltin( IconPath( "beginbutton" ) ); // beginButton
		public static Texture2D bluegroove                        => Icon.GetOrLoadFromBuiltin( IconPath( "bluegroove" ) ); // blueGroove
		public static Texture2D buildsettings_android             => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.android" ) ); // BuildSettings.Android
		public static Texture2D buildsettings_android_small       => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.android.small" ) ); // BuildSettings.Android.Small
		public static Texture2D buildsettings_broadcom            => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.broadcom" ) ); // BuildSettings.Broadcom
		public static Texture2D buildsettings_flashplayer         => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.flashplayer" ) ); // BuildSettings.FlashPlayer
		public static Texture2D buildsettings_flashplayer_small   => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.flashplayer.small" ) ); // BuildSettings.FlashPlayer.Small
		public static Texture2D buildsettings_iphone              => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.iphone" ) ); // BuildSettings.iPhone
		public static Texture2D buildsettings_iphone_small        => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.iphone.small" ) ); // BuildSettings.iPhone.Small
		public static Texture2D buildsettings_lumin               => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.lumin" ) ); // BuildSettings.Lumin
		public static Texture2D buildsettings_lumin_small         => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.lumin.small" ) ); // BuildSettings.Lumin.small
		public static Texture2D buildsettings_ps4                 => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.ps4" ) ); // BuildSettings.PS4
		public static Texture2D buildsettings_ps4_small           => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.ps4.small" ) ); // BuildSettings.PS4.Small
		public static Texture2D buildsettings_psp2                => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.psp2" ) ); // BuildSettings.PSP2
		public static Texture2D buildsettings_psp2_small          => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.psp2.small" ) ); // BuildSettings.PSP2.Small
		public static Texture2D buildsettings_selectedicon        => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.selectedicon" ) ); // BuildSettings.SelectedIcon
		public static Texture2D buildsettings_standalone          => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.standalone" ) ); // BuildSettings.Standalone
		public static Texture2D buildsettings_standalone_small    => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.standalone.small" ) ); // BuildSettings.Standalone.Small
		public static Texture2D buildsettings_tvos                => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.tvos" ) ); // BuildSettings.tvOS
		public static Texture2D buildsettings_tvos_small          => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.tvos.small" ) ); // BuildSettings.tvOS.Small
		public static Texture2D buildsettings_web                 => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.web" ) ); // BuildSettings.Web
		public static Texture2D buildsettings_web_small           => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.web.small" ) ); // BuildSettings.Web.Small
		public static Texture2D buildsettings_webgl               => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.webgl" ) ); // BuildSettings.WebGL
		public static Texture2D buildsettings_webgl_small         => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.webgl.small" ) ); // BuildSettings.WebGL.Small
		public static Texture2D buildsettings_xbox360             => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.xbox360" ) ); // BuildSettings.Xbox360
		public static Texture2D buildsettings_xbox360_small       => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.xbox360.small" ) ); // BuildSettings.Xbox360.Small
		public static Texture2D buildsettings_xboxone             => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.xboxone" ) ); // BuildSettings.XboxOne
		public static Texture2D buildsettings_xboxone_small       => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.xboxone.small" ) ); // BuildSettings.XboxOne.Small
		public static Texture2D checkerfloor                      => Icon.GetOrLoadFromBuiltin( IconPath( "checkerfloor" ) ); // CheckerFloor
		public static Texture2D cloudconnect                      => Icon.GetOrLoadFromBuiltin( IconPath( "cloudconnect" ) ); // CloudConnect
		public static Texture2D collab_fileadded                  => Icon.GetOrLoadFromBuiltin( IconPath( "collab.fileadded" ) ); // Collab.FileAdded
		public static Texture2D collab_fileconflict               => Icon.GetOrLoadFromBuiltin( IconPath( "collab.fileconflict" ) ); // Collab.FileConflict
		public static Texture2D collab_filedeleted                => Icon.GetOrLoadFromBuiltin( IconPath( "collab.filedeleted" ) ); // Collab.FileDeleted
		public static Texture2D collab_fileignored                => Icon.GetOrLoadFromBuiltin( IconPath( "collab.fileignored" ) ); // Collab.FileIgnored
		public static Texture2D collab_filemoved                  => Icon.GetOrLoadFromBuiltin( IconPath( "collab.filemoved" ) ); // Collab.FileMoved
		public static Texture2D collab_fileupdated                => Icon.GetOrLoadFromBuiltin( IconPath( "collab.fileupdated" ) ); // Collab.FileUpdated
		public static Texture2D collab_folderadded                => Icon.GetOrLoadFromBuiltin( IconPath( "collab.folderadded" ) ); // Collab.FolderAdded
		public static Texture2D collab_folderconflict             => Icon.GetOrLoadFromBuiltin( IconPath( "collab.folderconflict" ) ); // Collab.FolderConflict
		public static Texture2D collab_folderdeleted              => Icon.GetOrLoadFromBuiltin( IconPath( "collab.folderdeleted" ) ); // Collab.FolderDeleted
		public static Texture2D collab_folderignored              => Icon.GetOrLoadFromBuiltin( IconPath( "collab.folderignored" ) ); // Collab.FolderIgnored
		public static Texture2D collab_foldermoved                => Icon.GetOrLoadFromBuiltin( IconPath( "collab.foldermoved" ) ); // Collab.FolderMoved
		public static Texture2D collab_folderupdated              => Icon.GetOrLoadFromBuiltin( IconPath( "collab.folderupdated" ) ); // Collab.FolderUpdated
		public static Texture2D colorpicker_cyclecolor            => Icon.GetOrLoadFromBuiltin( IconPath( "colorpicker.cyclecolor" ) ); // ColorPicker.CycleColor
		public static Texture2D colorpicker_cycleslider           => Icon.GetOrLoadFromBuiltin( IconPath( "colorpicker.cycleslider" ) ); // ColorPicker.CycleSlider
		public static Texture2D console_erroricon                 => Icon.GetOrLoadFromBuiltin( IconPath( "console.erroricon" ) ); // console.erroricon
		public static Texture2D console_erroricon_sml             => Icon.GetOrLoadFromBuiltin( IconPath( "console.erroricon.sml" ) ); // console.erroricon.sml
		public static Texture2D console_infoicon                  => Icon.GetOrLoadFromBuiltin( IconPath( "console.infoicon" ) ); // console.infoicon
		public static Texture2D console_infoicon_sml              => Icon.GetOrLoadFromBuiltin( IconPath( "console.infoicon.sml" ) ); // console.infoicon.sml
		public static Texture2D console_warnicon                  => Icon.GetOrLoadFromBuiltin( IconPath( "console.warnicon" ) ); // console.warnicon
		public static Texture2D console_warnicon_sml              => Icon.GetOrLoadFromBuiltin( IconPath( "console.warnicon.sml" ) ); // console.warnicon.sml
		public static Texture2D curvekeyframe                     => Icon.GetOrLoadFromBuiltin( IconPath( "curvekeyframe" ) ); // curvekeyframe
		public static Texture2D curvekeyframeselected             => Icon.GetOrLoadFromBuiltin( IconPath( "curvekeyframeselected" ) ); // curvekeyframeselected
		public static Texture2D curvekeyframeselectedoverlay      => Icon.GetOrLoadFromBuiltin( IconPath( "curvekeyframeselectedoverlay" ) ); // curvekeyframeselectedoverlay
		public static Texture2D curvekeyframesemiselectedoverlay  => Icon.GetOrLoadFromBuiltin( IconPath( "curvekeyframesemiselectedoverlay" ) ); // curvekeyframesemiselectedoverlay
		public static Texture2D curvekeyframeweighted             => Icon.GetOrLoadFromBuiltin( IconPath( "curvekeyframeweighted" ) ); // curvekeyframeweighted
		public static Texture2D customsorting                     => Icon.GetOrLoadFromBuiltin( IconPath( "customsorting" ) ); // CustomSorting
		public static Texture2D customtool                        => Icon.GetOrLoadFromBuiltin( IconPath( "customtool" ) ); // CustomTool
		public static Texture2D customtool_2x                     => Icon.GetOrLoadFromBuiltin( IconPath( "customtool@2x" ) ); // CustomTool@2x
		public static Texture2D defaultsorting                    => Icon.GetOrLoadFromBuiltin( IconPath( "defaultsorting" ) ); // DefaultSorting
		public static Texture2D editcollider                      => Icon.GetOrLoadFromBuiltin( IconPath( "editcollider" ) ); // EditCollider
		public static Texture2D editcollision_16                  => Icon.GetOrLoadFromBuiltin( IconPath( "editcollision_16" ) ); // editcollision_16
		public static Texture2D editconstraints_16                => Icon.GetOrLoadFromBuiltin( IconPath( "editconstraints_16" ) ); // editconstraints_16
		public static Texture2D editicon_sml                      => Icon.GetOrLoadFromBuiltin( IconPath( "editicon.sml" ) ); // editicon.sml
		public static Texture2D endbutton_on                      => Icon.GetOrLoadFromBuiltin( IconPath( "endbutton-on" ) ); // endButton-On
		public static Texture2D endbutton                         => Icon.GetOrLoadFromBuiltin( IconPath( "endbutton" ) ); // endButton
		public static Texture2D eyedropper_large                  => Icon.GetOrLoadFromBuiltin( IconPath( "eyedropper.large" ) ); // eyeDropper.Large
		public static Texture2D eyedropper_sml                    => Icon.GetOrLoadFromBuiltin( IconPath( "eyedropper.sml" ) ); // eyeDropper.sml
		public static Texture2D favorite                          => Icon.GetOrLoadFromBuiltin( IconPath( "favorite" ) ); // Favorite
		public static Texture2D filterbylabel                     => Icon.GetOrLoadFromBuiltin( IconPath( "filterbylabel" ) ); // FilterByLabel
		public static Texture2D filterbytype                      => Icon.GetOrLoadFromBuiltin( IconPath( "filterbytype" ) ); // FilterByType
		public static Texture2D filterselectedonly                => Icon.GetOrLoadFromBuiltin( IconPath( "filterselectedonly" ) ); // FilterSelectedOnly
		public static Texture2D filterselectedonly_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "filterselectedonly@2x" ) ); // FilterSelectedOnly@2x
		public static Texture2D forward                           => Icon.GetOrLoadFromBuiltin( IconPath( "forward" ) ); // forward
		public static Texture2D forward_2x                        => Icon.GetOrLoadFromBuiltin( IconPath( "forward@2x" ) ); // forward@2x
		public static Texture2D gear                              => Icon.GetOrLoadFromBuiltin( IconPath( "gear" ) ); // GEAR
		public static Texture2D groove                            => Icon.GetOrLoadFromBuiltin( IconPath( "groove" ) ); // Groove
		public static Texture2D horizontalsplit                   => Icon.GetOrLoadFromBuiltin( IconPath( "horizontalsplit" ) ); // HorizontalSplit
		public static Texture2D icon_dropdown                     => Icon.GetOrLoadFromBuiltin( IconPath( "icon dropdown" ) ); // icon dropdown
		public static Texture2D inspectorlock                     => Icon.GetOrLoadFromBuiltin( IconPath( "inspectorlock" ) ); // InspectorLock
		public static Texture2D jointangularlimits                => Icon.GetOrLoadFromBuiltin( IconPath( "jointangularlimits" ) ); // JointAngularLimits
		public static Texture2D leftbracket                       => Icon.GetOrLoadFromBuiltin( IconPath( "leftbracket" ) ); // leftBracket
		public static Texture2D lighting                          => Icon.GetOrLoadFromBuiltin( IconPath( "lighting" ) ); // Lighting
		public static Texture2D lightmapeditor_windowtitle        => Icon.GetOrLoadFromBuiltin( IconPath( "lightmapeditor.windowtitle" ) ); // LightmapEditor.WindowTitle
		public static Texture2D lookdevcenterlight                => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevcenterlight" ) ); // LookDevCenterLight
		public static Texture2D lookdevclose                      => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevclose" ) ); // LookDevClose
		public static Texture2D lookdevclose_2x                   => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevclose@2x" ) ); // LookDevClose@2x
		public static Texture2D lookdevenvrotation                => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevenvrotation" ) ); // LookDevEnvRotation
		public static Texture2D lookdevenvrotation_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevenvrotation@2x" ) ); // LookDevEnvRotation@2x
		public static Texture2D lookdevmirrorviewsactive          => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevmirrorviewsactive" ) ); // LookDevMirrorViewsActive
		public static Texture2D lookdevmirrorviewsactive_2x       => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevmirrorviewsactive@2x" ) ); // LookDevMirrorViewsActive@2x
		public static Texture2D lookdevmirrorviewsinactive        => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevmirrorviewsinactive" ) ); // LookDevMirrorViewsInactive
		public static Texture2D lookdevmirrorviewsinactive_2x     => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevmirrorviewsinactive@2x" ) ); // LookDevMirrorViewsInactive@2x
		public static Texture2D lookdevobjrotation                => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevobjrotation" ) ); // LookDevObjRotation
		public static Texture2D lookdevobjrotation_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevobjrotation@2x" ) ); // LookDevObjRotation@2x
		public static Texture2D lookdevpaneoption                 => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevpaneoption" ) ); // LookDevPaneOption
		public static Texture2D lookdevpaneoption_2x              => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevpaneoption@2x" ) ); // LookDevPaneOption@2x
		public static Texture2D lookdevresetenv                   => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevresetenv" ) ); // LookDevResetEnv
		public static Texture2D lookdevresetenv_2x                => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevresetenv@2x" ) ); // LookDevResetEnv@2x
		public static Texture2D lookdevshadow                     => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevshadow" ) ); // LookDevShadow
		public static Texture2D lookdevshadow_2x                  => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevshadow@2x" ) ); // LookDevShadow@2x
		public static Texture2D lookdevsidebyside                 => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevsidebyside" ) ); // LookDevSideBySide
		public static Texture2D lookdevsidebyside_2x              => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevsidebyside@2x" ) ); // LookDevSideBySide@2x
		public static Texture2D lookdevsingle1                    => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevsingle1" ) ); // LookDevSingle1
		public static Texture2D lookdevsingle1_2x                 => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevsingle1@2x" ) ); // LookDevSingle1@2x
		public static Texture2D lookdevsingle2                    => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevsingle2" ) ); // LookDevSingle2
		public static Texture2D lookdevsingle2_2x                 => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevsingle2@2x" ) ); // LookDevSingle2@2x
		public static Texture2D lookdevsplit                      => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevsplit" ) ); // LookDevSplit
		public static Texture2D lookdevsplit_2x                   => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevsplit@2x" ) ); // LookDevSplit@2x
		public static Texture2D lookdevzone                       => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevzone" ) ); // LookDevZone
		public static Texture2D lookdevzone_2x                    => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevzone@2x" ) ); // LookDevZone@2x
		public static Texture2D mainstageview                     => Icon.GetOrLoadFromBuiltin( IconPath( "mainstageview" ) ); // MainStageView
		public static Texture2D mainstageview_2x                  => Icon.GetOrLoadFromBuiltin( IconPath( "mainstageview@2x" ) ); // MainStageView@2x
		public static Texture2D mirror                            => Icon.GetOrLoadFromBuiltin( IconPath( "mirror" ) ); // Mirror
		public static Texture2D monologo                          => Icon.GetOrLoadFromBuiltin( IconPath( "monologo" ) ); // monologo
		public static Texture2D movetool_on                       => Icon.GetOrLoadFromBuiltin( IconPath( "movetool on" ) ); // MoveTool on
		public static Texture2D movetool                          => Icon.GetOrLoadFromBuiltin( IconPath( "movetool" ) ); // MoveTool
		public static Texture2D navigation                        => Icon.GetOrLoadFromBuiltin( IconPath( "navigation" ) ); // Navigation
		public static Texture2D occlusion                         => Icon.GetOrLoadFromBuiltin( IconPath( "occlusion" ) ); // Occlusion
		public static Texture2D p4_addedlocal                     => Icon.GetOrLoadFromBuiltin( IconPath( "p4_addedlocal" ) ); // P4_AddedLocal
		public static Texture2D p4_addedremote                    => Icon.GetOrLoadFromBuiltin( IconPath( "p4_addedremote" ) ); // P4_AddedRemote
		public static Texture2D p4_checkoutlocal                  => Icon.GetOrLoadFromBuiltin( IconPath( "p4_checkoutlocal" ) ); // P4_CheckOutLocal
		public static Texture2D p4_checkoutremote                 => Icon.GetOrLoadFromBuiltin( IconPath( "p4_checkoutremote" ) ); // P4_CheckOutRemote
		public static Texture2D p4_conflicted                     => Icon.GetOrLoadFromBuiltin( IconPath( "p4_conflicted" ) ); // P4_Conflicted
		public static Texture2D p4_deletedlocal                   => Icon.GetOrLoadFromBuiltin( IconPath( "p4_deletedlocal" ) ); // P4_DeletedLocal
		public static Texture2D p4_deletedremote                  => Icon.GetOrLoadFromBuiltin( IconPath( "p4_deletedremote" ) ); // P4_DeletedRemote
		public static Texture2D p4_local                          => Icon.GetOrLoadFromBuiltin( IconPath( "p4_local" ) ); // P4_Local
		public static Texture2D p4_lockedlocal                    => Icon.GetOrLoadFromBuiltin( IconPath( "p4_lockedlocal" ) ); // P4_LockedLocal
		public static Texture2D p4_lockedremote                   => Icon.GetOrLoadFromBuiltin( IconPath( "p4_lockedremote" ) ); // P4_LockedRemote
		public static Texture2D p4_outofsync                      => Icon.GetOrLoadFromBuiltin( IconPath( "p4_outofsync" ) ); // P4_OutOfSync
		public static Texture2D particle_effect                   => Icon.GetOrLoadFromBuiltin( IconPath( "particle effect" ) ); // Particle Effect
		public static Texture2D particleshapetool_on              => Icon.GetOrLoadFromBuiltin( IconPath( "particleshapetool on" ) ); // ParticleShapeTool On
		public static Texture2D particleshapetool_on_2x           => Icon.GetOrLoadFromBuiltin( IconPath( "particleshapetool on@2x" ) ); // ParticleShapeTool On@2x
		public static Texture2D particleshapetool_on_3x           => Icon.GetOrLoadFromBuiltin( IconPath( "particleshapetool on@3x" ) ); // ParticleShapeTool On@3x
		public static Texture2D particleshapetool_on_4x           => Icon.GetOrLoadFromBuiltin( IconPath( "particleshapetool on@4x" ) ); // ParticleShapeTool On@4x
		public static Texture2D particleshapetool                 => Icon.GetOrLoadFromBuiltin( IconPath( "particleshapetool" ) ); // ParticleShapeTool
		public static Texture2D particleshapetool_2x              => Icon.GetOrLoadFromBuiltin( IconPath( "particleshapetool@2x" ) ); // ParticleShapeTool@2x
		public static Texture2D particleshapetool_3x              => Icon.GetOrLoadFromBuiltin( IconPath( "particleshapetool@3x" ) ); // ParticleShapeTool@3x
		public static Texture2D particleshapetool_4x              => Icon.GetOrLoadFromBuiltin( IconPath( "particleshapetool@4x" ) ); // ParticleShapeTool@4x
		public static Texture2D pausebutton_on                    => Icon.GetOrLoadFromBuiltin( IconPath( "pausebutton on" ) ); // PauseButton On
		public static Texture2D pausebutton                       => Icon.GetOrLoadFromBuiltin( IconPath( "pausebutton" ) ); // PauseButton
		public static Texture2D playbutton_on                     => Icon.GetOrLoadFromBuiltin( IconPath( "playbutton on" ) ); // PlayButton On
		public static Texture2D playbutton                        => Icon.GetOrLoadFromBuiltin( IconPath( "playbutton" ) ); // PlayButton
		public static Texture2D playbuttonprofile_on              => Icon.GetOrLoadFromBuiltin( IconPath( "playbuttonprofile on" ) ); // PlayButtonProfile On
		public static Texture2D playbuttonprofile                 => Icon.GetOrLoadFromBuiltin( IconPath( "playbuttonprofile" ) ); // PlayButtonProfile
		public static Texture2D playloopoff                       => Icon.GetOrLoadFromBuiltin( IconPath( "playloopoff" ) ); // playLoopOff
		public static Texture2D playloopon                        => Icon.GetOrLoadFromBuiltin( IconPath( "playloopon" ) ); // playLoopOn
		public static Texture2D preaudioautoplayoff               => Icon.GetOrLoadFromBuiltin( IconPath( "preaudioautoplayoff" ) ); // preAudioAutoPlayOff
		public static Texture2D preaudioautoplayon                => Icon.GetOrLoadFromBuiltin( IconPath( "preaudioautoplayon" ) ); // preAudioAutoPlayOn
		public static Texture2D preaudioloopoff                   => Icon.GetOrLoadFromBuiltin( IconPath( "preaudioloopoff" ) ); // preAudioLoopOff
		public static Texture2D preaudioloopon                    => Icon.GetOrLoadFromBuiltin( IconPath( "preaudioloopon" ) ); // preAudioLoopOn
		public static Texture2D preaudioplayoff                   => Icon.GetOrLoadFromBuiltin( IconPath( "preaudioplayoff" ) ); // preAudioPlayOff
		public static Texture2D preaudioplayon                    => Icon.GetOrLoadFromBuiltin( IconPath( "preaudioplayon" ) ); // preAudioPlayOn
		public static Texture2D prematcube                        => Icon.GetOrLoadFromBuiltin( IconPath( "prematcube" ) ); // PreMatCube
		public static Texture2D prematcylinder                    => Icon.GetOrLoadFromBuiltin( IconPath( "prematcylinder" ) ); // PreMatCylinder
		public static Texture2D prematlight0                      => Icon.GetOrLoadFromBuiltin( IconPath( "prematlight0" ) ); // PreMatLight0
		public static Texture2D prematlight1                      => Icon.GetOrLoadFromBuiltin( IconPath( "prematlight1" ) ); // PreMatLight1
		public static Texture2D prematsphere                      => Icon.GetOrLoadFromBuiltin( IconPath( "prematsphere" ) ); // PreMatSphere
		public static Texture2D premattorus                       => Icon.GetOrLoadFromBuiltin( IconPath( "premattorus" ) ); // PreMatTorus
		public static Texture2D preset_context                    => Icon.GetOrLoadFromBuiltin( IconPath( "preset.context" ) ); // Preset.Context
		public static Texture2D pretexturealpha                   => Icon.GetOrLoadFromBuiltin( IconPath( "pretexturealpha" ) ); // PreTextureAlpha
		public static Texture2D pretexturemipmaphigh              => Icon.GetOrLoadFromBuiltin( IconPath( "pretexturemipmaphigh" ) ); // PreTextureMipMapHigh
		public static Texture2D pretexturemipmaplow               => Icon.GetOrLoadFromBuiltin( IconPath( "pretexturemipmaplow" ) ); // PreTextureMipMapLow
		public static Texture2D pretexturergb                     => Icon.GetOrLoadFromBuiltin( IconPath( "pretexturergb" ) ); // PreTextureRGB
		public static Texture2D profiler_audio                    => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.audio" ) ); // Profiler.Audio
		public static Texture2D profiler_cpu                      => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.cpu" ) ); // Profiler.CPU
		public static Texture2D profiler_firstframe               => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.firstframe" ) ); // Profiler.FirstFrame
		public static Texture2D profiler_gpu                      => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.gpu" ) ); // Profiler.GPU
		public static Texture2D profiler_lastframe                => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.lastframe" ) ); // Profiler.LastFrame
		public static Texture2D profiler_memory                   => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.memory" ) ); // Profiler.Memory
		public static Texture2D profiler_nextframe                => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.nextframe" ) ); // Profiler.NextFrame
		public static Texture2D profiler_physics                  => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.physics" ) ); // Profiler.Physics
		public static Texture2D profiler_prevframe                => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.prevframe" ) ); // Profiler.PrevFrame
		public static Texture2D profiler_record                   => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.record" ) ); // Profiler.Record
		public static Texture2D profiler_rendering                => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.rendering" ) ); // Profiler.Rendering
		public static Texture2D profiler_video                    => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.video" ) ); // Profiler.Video
		public static Texture2D profilercolumn_warningcount       => Icon.GetOrLoadFromBuiltin( IconPath( "profilercolumn.warningcount" ) ); // ProfilerColumn.WarningCount
		public static Texture2D project                           => Icon.GetOrLoadFromBuiltin( IconPath( "project" ) ); // Project
		public static Texture2D recttool_on                       => Icon.GetOrLoadFromBuiltin( IconPath( "recttool on" ) ); // RectTool On
		public static Texture2D recttool                          => Icon.GetOrLoadFromBuiltin( IconPath( "recttool" ) ); // RectTool
		public static Texture2D recttransformblueprint            => Icon.GetOrLoadFromBuiltin( IconPath( "recttransformblueprint" ) ); // RectTransformBlueprint
		public static Texture2D recttransformraw                  => Icon.GetOrLoadFromBuiltin( IconPath( "recttransformraw" ) ); // RectTransformRaw
		public static Texture2D redgroove                         => Icon.GetOrLoadFromBuiltin( IconPath( "redgroove" ) ); // redGroove
		public static Texture2D refresh                           => Icon.GetOrLoadFromBuiltin( IconPath( "refresh" ) ); // Refresh
		public static Texture2D renderdoc                         => Icon.GetOrLoadFromBuiltin( IconPath( "renderdoc" ) ); // renderdoc
		public static Texture2D rightbracket                      => Icon.GetOrLoadFromBuiltin( IconPath( "rightbracket" ) ); // rightBracket
		public static Texture2D rotatetool_on                     => Icon.GetOrLoadFromBuiltin( IconPath( "rotatetool on" ) ); // RotateTool On
		public static Texture2D rotatetool                        => Icon.GetOrLoadFromBuiltin( IconPath( "rotatetool" ) ); // RotateTool
		public static Texture2D scaletool_on                      => Icon.GetOrLoadFromBuiltin( IconPath( "scaletool on" ) ); // ScaleTool On
		public static Texture2D scaletool                         => Icon.GetOrLoadFromBuiltin( IconPath( "scaletool" ) ); // ScaleTool
		public static Texture2D sceneview2d                       => Icon.GetOrLoadFromBuiltin( IconPath( "sceneview2d" ) ); // SceneView2D
		public static Texture2D sceneview2d_2x                    => Icon.GetOrLoadFromBuiltin( IconPath( "sceneview2d@2x" ) ); // SceneView2D@2x
		public static Texture2D sceneviewalpha                    => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewalpha" ) ); // SceneViewAlpha
		public static Texture2D sceneviewaudio                    => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewaudio" ) ); // SceneViewAudio
		public static Texture2D sceneviewaudio_2x                 => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewaudio@2x" ) ); // SceneViewAudio@2x
		public static Texture2D sceneviewcamera                   => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewcamera" ) ); // SceneViewCamera
		public static Texture2D sceneviewcamera_2x                => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewcamera@2x" ) ); // SceneViewCamera@2x
		public static Texture2D sceneviewfx                       => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewfx" ) ); // SceneViewFx
		public static Texture2D sceneviewfx_2x                    => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewfx@2x" ) ); // SceneViewFX@2x
		public static Texture2D sceneviewlighting                 => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewlighting" ) ); // SceneViewLighting
		public static Texture2D sceneviewlighting_2x              => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewlighting@2x" ) ); // SceneViewLighting@2x
		public static Texture2D sceneviewortho                    => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewortho" ) ); // SceneViewOrtho
		public static Texture2D sceneviewrgb                      => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewrgb" ) ); // SceneViewRGB
		public static Texture2D sceneviewtools                    => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewtools" ) ); // SceneViewTools
		public static Texture2D sceneviewtools_2x                 => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewtools@2x" ) ); // SceneViewTools@2x
		public static Texture2D sceneviewvisibility               => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewvisibility" ) ); // SceneViewVisibility
		public static Texture2D sceneviewvisibility_2x            => Icon.GetOrLoadFromBuiltin( IconPath( "sceneviewvisibility@2x" ) ); // SceneViewVisibility@2x
		public static Texture2D scenevis_hidden_mixed             => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_hidden-mixed" ) ); // scenevis_hidden-mixed
		public static Texture2D scenevis_hidden_mixed_2x          => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_hidden-mixed@2x" ) ); // scenevis_hidden-mixed@2x
		public static Texture2D scenevis_hidden                   => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_hidden" ) ); // scenevis_hidden
		public static Texture2D scenevis_hidden_2x                => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_hidden@2x" ) ); // scenevis_hidden@2x
		public static Texture2D scenevis_hidden_hover             => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_hidden_hover" ) ); // scenevis_hidden_hover
		public static Texture2D scenevis_hidden_hover_2x          => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_hidden_hover@2x" ) ); // scenevis_hidden_hover@2x
		public static Texture2D scenevis_scene_hover              => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_scene_hover" ) ); // scenevis_scene_hover
		public static Texture2D scenevis_scene_hover_2x           => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_scene_hover@2x" ) ); // scenevis_scene_hover@2x
		public static Texture2D scenevis_visible_mixed            => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_visible-mixed" ) ); // scenevis_visible-mixed
		public static Texture2D scenevis_visible_mixed_2x         => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_visible-mixed@2x" ) ); // scenevis_visible-mixed@2x
		public static Texture2D scenevis_visible                  => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_visible" ) ); // scenevis_visible
		public static Texture2D scenevis_visible_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_visible@2x" ) ); // scenevis_visible@2x
		public static Texture2D scenevis_visible_hover            => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_visible_hover" ) ); // scenevis_visible_hover
		public static Texture2D scenevis_visible_hover_2x         => Icon.GetOrLoadFromBuiltin( IconPath( "scenevis_visible_hover@2x" ) ); // scenevis_visible_hover@2x
		public static Texture2D scrollshadow                      => Icon.GetOrLoadFromBuiltin( IconPath( "scrollshadow" ) ); // ScrollShadow
		public static Texture2D settings                          => Icon.GetOrLoadFromBuiltin( IconPath( "settings" ) ); // Settings
		public static Texture2D settingsicon                      => Icon.GetOrLoadFromBuiltin( IconPath( "settingsicon" ) ); // SettingsIcon
		public static Texture2D socialnetworks_facebookshare      => Icon.GetOrLoadFromBuiltin( IconPath( "socialnetworks.facebookshare" ) ); // SocialNetworks.FacebookShare
		public static Texture2D socialnetworks_linkedinshare      => Icon.GetOrLoadFromBuiltin( IconPath( "socialnetworks.linkedinshare" ) ); // SocialNetworks.LinkedInShare
		public static Texture2D socialnetworks_tweet              => Icon.GetOrLoadFromBuiltin( IconPath( "socialnetworks.tweet" ) ); // SocialNetworks.Tweet
		public static Texture2D socialnetworks_udnopen            => Icon.GetOrLoadFromBuiltin( IconPath( "socialnetworks.udnopen" ) ); // SocialNetworks.UDNOpen
		public static Texture2D speedscale                        => Icon.GetOrLoadFromBuiltin( IconPath( "speedscale" ) ); // SpeedScale
		public static Texture2D stepbutton_on                     => Icon.GetOrLoadFromBuiltin( IconPath( "stepbutton on" ) ); // StepButton On
		public static Texture2D stepbutton                        => Icon.GetOrLoadFromBuiltin( IconPath( "stepbutton" ) ); // StepButton
		public static Texture2D stepleftbutton_on                 => Icon.GetOrLoadFromBuiltin( IconPath( "stepleftbutton-on" ) ); // StepLeftButton-On
		public static Texture2D stepleftbutton                    => Icon.GetOrLoadFromBuiltin( IconPath( "stepleftbutton" ) ); // StepLeftButton
		public static Texture2D svn_addedlocal                    => Icon.GetOrLoadFromBuiltin( IconPath( "svn_addedlocal" ) ); // SVN_AddedLocal
		public static Texture2D svn_conflicted                    => Icon.GetOrLoadFromBuiltin( IconPath( "svn_conflicted" ) ); // SVN_Conflicted
		public static Texture2D svn_deletedlocal                  => Icon.GetOrLoadFromBuiltin( IconPath( "svn_deletedlocal" ) ); // SVN_DeletedLocal
		public static Texture2D svn_local                         => Icon.GetOrLoadFromBuiltin( IconPath( "svn_local" ) ); // SVN_Local
		public static Texture2D svn_lockedlocal                   => Icon.GetOrLoadFromBuiltin( IconPath( "svn_lockedlocal" ) ); // SVN_LockedLocal
		public static Texture2D svn_outofsync                     => Icon.GetOrLoadFromBuiltin( IconPath( "svn_outofsync" ) ); // SVN_OutOfSync
		public static Texture2D tab_next                          => Icon.GetOrLoadFromBuiltin( IconPath( "tab_next" ) ); // tab_next
		public static Texture2D tab_next_2x                       => Icon.GetOrLoadFromBuiltin( IconPath( "tab_next@2x" ) ); // tab_next@2x
		public static Texture2D tab_prev                          => Icon.GetOrLoadFromBuiltin( IconPath( "tab_prev" ) ); // tab_prev
		public static Texture2D tab_prev_2x                       => Icon.GetOrLoadFromBuiltin( IconPath( "tab_prev@2x" ) ); // tab_prev@2x
		public static Texture2D terraininspector_terraintoollower_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoollower on" ) ); // TerrainInspector.TerrainToolLower On
		public static Texture2D terraininspector_terraintoolloweralt  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolloweralt" ) ); // TerrainInspector.TerrainToolLowerAlt
		public static Texture2D terraininspector_terraintoolplants_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolplants on" ) ); // TerrainInspector.TerrainToolPlants On
		public static Texture2D terraininspector_terraintoolplants  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolplants" ) ); // TerrainInspector.TerrainToolPlants
		public static Texture2D terraininspector_terraintoolplantsalt_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolplantsalt on" ) ); // TerrainInspector.TerrainToolPlantsAlt On
		public static Texture2D terraininspector_terraintoolplantsalt  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolplantsalt" ) ); // TerrainInspector.TerrainToolPlantsAlt
		public static Texture2D terraininspector_terraintoolraise_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolraise on" ) ); // TerrainInspector.TerrainToolRaise On
		public static Texture2D terraininspector_terraintoolraise  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolraise" ) ); // TerrainInspector.TerrainToolRaise
		public static Texture2D terraininspector_terraintoolsetheight_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsetheight on" ) ); // TerrainInspector.TerrainToolSetheight On
		public static Texture2D terraininspector_terraintoolsetheight  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsetheight" ) ); // TerrainInspector.TerrainToolSetheight
		public static Texture2D terraininspector_terraintoolsetheightalt_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsetheightalt on" ) ); // TerrainInspector.TerrainToolSetheightAlt On
		public static Texture2D terraininspector_terraintoolsetheightalt  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsetheightalt" ) ); // TerrainInspector.TerrainToolSetheightAlt
		public static Texture2D terraininspector_terraintoolsettings_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsettings on" ) ); // TerrainInspector.TerrainToolSettings On
		public static Texture2D terraininspector_terraintoolsettings  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsettings" ) ); // TerrainInspector.TerrainToolSettings
		public static Texture2D terraininspector_terraintoolsmoothheight_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsmoothheight on" ) ); // TerrainInspector.TerrainToolSmoothHeight On
		public static Texture2D terraininspector_terraintoolsmoothheight  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsmoothheight" ) ); // TerrainInspector.TerrainToolSmoothHeight
		public static Texture2D terraininspector_terraintoolsplat_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsplat on" ) ); // TerrainInspector.TerrainToolSplat On
		public static Texture2D terraininspector_terraintoolsplat  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsplat" ) ); // TerrainInspector.TerrainToolSplat
		public static Texture2D terraininspector_terraintoolsplatalt_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsplatalt on" ) ); // TerrainInspector.TerrainToolSplatAlt On
		public static Texture2D terraininspector_terraintoolsplatalt  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsplatalt" ) ); // TerrainInspector.TerrainToolSplatAlt
		public static Texture2D terraininspector_terraintooltrees_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintooltrees on" ) ); // TerrainInspector.TerrainToolTrees On
		public static Texture2D terraininspector_terraintooltrees  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintooltrees" ) ); // TerrainInspector.TerrainToolTrees
		public static Texture2D terraininspector_terraintooltreesalt_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintooltreesalt on" ) ); // TerrainInspector.TerrainToolTreesAlt On
		public static Texture2D terraininspector_terraintooltreesalt  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintooltreesalt" ) ); // TerrainInspector.TerrainToolTreesAlt
		public static Texture2D timelinedigin                     => Icon.GetOrLoadFromBuiltin( IconPath( "timelinedigin" ) ); // TimelineDigIn
		public static Texture2D timelineeditmodemixoff            => Icon.GetOrLoadFromBuiltin( IconPath( "timelineeditmodemixoff" ) ); // TimelineEditModeMixOFF
		public static Texture2D timelineeditmodemixon             => Icon.GetOrLoadFromBuiltin( IconPath( "timelineeditmodemixon" ) ); // TimelineEditModeMixON
		public static Texture2D timelineeditmodereplaceoff        => Icon.GetOrLoadFromBuiltin( IconPath( "timelineeditmodereplaceoff" ) ); // TimelineEditModeReplaceOFF
		public static Texture2D timelineeditmodereplaceon         => Icon.GetOrLoadFromBuiltin( IconPath( "timelineeditmodereplaceon" ) ); // TimelineEditModeReplaceON
		public static Texture2D timelineeditmoderippleoff         => Icon.GetOrLoadFromBuiltin( IconPath( "timelineeditmoderippleoff" ) ); // TimelineEditModeRippleOFF
		public static Texture2D timelineeditmoderippleon          => Icon.GetOrLoadFromBuiltin( IconPath( "timelineeditmoderippleon" ) ); // TimelineEditModeRippleON
		public static Texture2D timelineheadermarkericon          => Icon.GetOrLoadFromBuiltin( IconPath( "timelineheadermarkericon" ) ); // TimelineHeaderMarkerIcon
		public static Texture2D timelinemarkerareabuttondisabled  => Icon.GetOrLoadFromBuiltin( IconPath( "timelinemarkerareabuttondisabled" ) ); // TimelineMarkerAreaButtonDisabled
		public static Texture2D timelinemarkerareabuttonenabled   => Icon.GetOrLoadFromBuiltin( IconPath( "timelinemarkerareabuttonenabled" ) ); // TimelineMarkerAreaButtonEnabled
		public static Texture2D timelineselector                  => Icon.GetOrLoadFromBuiltin( IconPath( "timelineselector" ) ); // TimelineSelector
		public static Texture2D toggleuvoverlay                   => Icon.GetOrLoadFromBuiltin( IconPath( "toggleuvoverlay" ) ); // ToggleUVOverlay
		public static Texture2D toggleuvoverlay_2x                => Icon.GetOrLoadFromBuiltin( IconPath( "toggleuvoverlay@2x" ) ); // ToggleUVOverlay@2x
		public static Texture2D toolbar_minus                     => Icon.GetOrLoadFromBuiltin( IconPath( "toolbar minus" ) ); // Toolbar Minus
		public static Texture2D toolbar_plus_more                 => Icon.GetOrLoadFromBuiltin( IconPath( "toolbar plus more" ) ); // Toolbar Plus More
		public static Texture2D toolbar_plus                      => Icon.GetOrLoadFromBuiltin( IconPath( "toolbar plus" ) ); // Toolbar Plus
		public static Texture2D toolhandlecenter                  => Icon.GetOrLoadFromBuiltin( IconPath( "toolhandlecenter" ) ); // ToolHandleCenter
		public static Texture2D toolhandleglobal                  => Icon.GetOrLoadFromBuiltin( IconPath( "toolhandleglobal" ) ); // ToolHandleGlobal
		public static Texture2D toolhandlelocal                   => Icon.GetOrLoadFromBuiltin( IconPath( "toolhandlelocal" ) ); // ToolHandleLocal
		public static Texture2D toolhandlepivot                   => Icon.GetOrLoadFromBuiltin( IconPath( "toolhandlepivot" ) ); // ToolHandlePivot
		public static Texture2D toolsicon                         => Icon.GetOrLoadFromBuiltin( IconPath( "toolsicon" ) ); // ToolsIcon
		public static Texture2D tranp                             => Icon.GetOrLoadFromBuiltin( IconPath( "tranp" ) ); // tranp
		public static Texture2D transformtool_on                  => Icon.GetOrLoadFromBuiltin( IconPath( "transformtool on" ) ); // TransformTool On
		public static Texture2D transformtool                     => Icon.GetOrLoadFromBuiltin( IconPath( "transformtool" ) ); // TransformTool
		public static Texture2D tree_icon                         => Icon.GetOrLoadFromBuiltin( IconPath( "tree_icon" ) ); // tree_icon
		public static Texture2D tree_icon_branch                  => Icon.GetOrLoadFromBuiltin( IconPath( "tree_icon_branch" ) ); // tree_icon_branch
		public static Texture2D tree_icon_branch_frond            => Icon.GetOrLoadFromBuiltin( IconPath( "tree_icon_branch_frond" ) ); // tree_icon_branch_frond
		public static Texture2D tree_icon_frond                   => Icon.GetOrLoadFromBuiltin( IconPath( "tree_icon_frond" ) ); // tree_icon_frond
		public static Texture2D tree_icon_leaf                    => Icon.GetOrLoadFromBuiltin( IconPath( "tree_icon_leaf" ) ); // tree_icon_leaf
		public static Texture2D treeeditor_addbranches            => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.addbranches" ) ); // TreeEditor.AddBranches
		public static Texture2D treeeditor_addleaves              => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.addleaves" ) ); // TreeEditor.AddLeaves
		public static Texture2D treeeditor_branch_on              => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branch on" ) ); // TreeEditor.Branch On
		public static Texture2D treeeditor_branch                 => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branch" ) ); // TreeEditor.Branch
		public static Texture2D treeeditor_branchfreehand_on      => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branchfreehand on" ) ); // TreeEditor.BranchFreeHand On
		public static Texture2D treeeditor_branchfreehand         => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branchfreehand" ) ); // TreeEditor.BranchFreeHand
		public static Texture2D treeeditor_branchrotate_on        => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branchrotate on" ) ); // TreeEditor.BranchRotate On
		public static Texture2D treeeditor_branchrotate           => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branchrotate" ) ); // TreeEditor.BranchRotate
		public static Texture2D treeeditor_branchscale_on         => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branchscale on" ) ); // TreeEditor.BranchScale On
		public static Texture2D treeeditor_branchscale            => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branchscale" ) ); // TreeEditor.BranchScale
		public static Texture2D treeeditor_branchtranslate_on     => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branchtranslate on" ) ); // TreeEditor.BranchTranslate On
		public static Texture2D treeeditor_branchtranslate        => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.branchtranslate" ) ); // TreeEditor.BranchTranslate
		public static Texture2D treeeditor_distribution_on        => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.distribution on" ) ); // TreeEditor.Distribution On
		public static Texture2D treeeditor_distribution           => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.distribution" ) ); // TreeEditor.Distribution
		public static Texture2D treeeditor_duplicate              => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.duplicate" ) ); // TreeEditor.Duplicate
		public static Texture2D treeeditor_geometry_on            => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.geometry on" ) ); // TreeEditor.Geometry On
		public static Texture2D treeeditor_geometry               => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.geometry" ) ); // TreeEditor.Geometry
		public static Texture2D treeeditor_leaf_on                => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leaf on" ) ); // TreeEditor.Leaf On
		public static Texture2D treeeditor_leaf                   => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leaf" ) ); // TreeEditor.Leaf
		public static Texture2D treeeditor_leaffreehand_on        => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leaffreehand on" ) ); // TreeEditor.LeafFreeHand On
		public static Texture2D treeeditor_leaffreehand           => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leaffreehand" ) ); // TreeEditor.LeafFreeHand
		public static Texture2D treeeditor_leafrotate_on          => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leafrotate on" ) ); // TreeEditor.LeafRotate On
		public static Texture2D treeeditor_leafrotate             => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leafrotate" ) ); // TreeEditor.LeafRotate
		public static Texture2D treeeditor_leafscale_on           => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leafscale on" ) ); // TreeEditor.LeafScale On
		public static Texture2D treeeditor_leafscale              => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leafscale" ) ); // TreeEditor.LeafScale
		public static Texture2D treeeditor_leaftranslate_on       => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leaftranslate on" ) ); // TreeEditor.LeafTranslate On
		public static Texture2D treeeditor_leaftranslate          => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.leaftranslate" ) ); // TreeEditor.LeafTranslate
		public static Texture2D treeeditor_material_on            => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.material on" ) ); // TreeEditor.Material On
		public static Texture2D treeeditor_material               => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.material" ) ); // TreeEditor.Material
		public static Texture2D treeeditor_refresh                => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.refresh" ) ); // TreeEditor.Refresh
		public static Texture2D treeeditor_trash                  => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.trash" ) ); // TreeEditor.Trash
		public static Texture2D treeeditor_wind_on                => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.wind on" ) ); // TreeEditor.Wind On
		public static Texture2D treeeditor_wind                   => Icon.GetOrLoadFromBuiltin( IconPath( "treeeditor.wind" ) ); // TreeEditor.Wind
		public static Texture2D unityeditor_animationwindow       => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.animationwindow" ) ); // UnityEditor.AnimationWindow
		public static Texture2D unityeditor_consolewindow         => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.consolewindow" ) ); // UnityEditor.ConsoleWindow
		public static Texture2D unityeditor_debuginspectorwindow  => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.debuginspectorwindow" ) ); // UnityEditor.DebugInspectorWindow
		public static Texture2D unityeditor_finddependencies      => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.finddependencies" ) ); // UnityEditor.FindDependencies
		public static Texture2D unityeditor_gameview              => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.gameview" ) ); // UnityEditor.GameView
		public static Texture2D unityeditor_hierarchywindow       => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.hierarchywindow" ) ); // UnityEditor.HierarchyWindow
		public static Texture2D unityeditor_inspectorwindow       => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.inspectorwindow" ) ); // UnityEditor.InspectorWindow
		public static Texture2D unityeditor_lookdevview           => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.lookdevview" ) ); // UnityEditor.LookDevView
		public static Texture2D unityeditor_profilerwindow        => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.profilerwindow" ) ); // UnityEditor.ProfilerWindow
		public static Texture2D unityeditor_scenehierarchywindow  => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.scenehierarchywindow" ) ); // UnityEditor.SceneHierarchyWindow
		public static Texture2D unityeditor_sceneview             => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.sceneview" ) ); // UnityEditor.SceneView
		public static Texture2D unityeditor_timeline_timelinewindow  => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.timeline.timelinewindow" ) ); // UnityEditor.Timeline.TimelineWindow
		public static Texture2D unityeditor_versioncontrol        => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.versioncontrol" ) ); // UnityEditor.VersionControl
		public static Texture2D unitylogo                         => Icon.GetOrLoadFromBuiltin( IconPath( "unitylogo" ) ); // UnityLogo
		public static Texture2D verticalsplit                     => Icon.GetOrLoadFromBuiltin( IconPath( "verticalsplit" ) ); // VerticalSplit
		public static Texture2D viewtoolmove_on                   => Icon.GetOrLoadFromBuiltin( IconPath( "viewtoolmove on" ) ); // ViewToolMove On
		public static Texture2D viewtoolmove                      => Icon.GetOrLoadFromBuiltin( IconPath( "viewtoolmove" ) ); // ViewToolMove
		public static Texture2D viewtoolorbit_on                  => Icon.GetOrLoadFromBuiltin( IconPath( "viewtoolorbit on" ) ); // ViewToolOrbit On
		public static Texture2D viewtoolorbit                     => Icon.GetOrLoadFromBuiltin( IconPath( "viewtoolorbit" ) ); // ViewToolOrbit
		public static Texture2D viewtoolzoom_on                   => Icon.GetOrLoadFromBuiltin( IconPath( "viewtoolzoom on" ) ); // ViewToolZoom On
		public static Texture2D viewtoolzoom                      => Icon.GetOrLoadFromBuiltin( IconPath( "viewtoolzoom" ) ); // ViewToolZoom
		public static Texture2D visibilityoff                     => Icon.GetOrLoadFromBuiltin( IconPath( "visibilityoff" ) ); // VisibilityOff
		public static Texture2D visibilityon                      => Icon.GetOrLoadFromBuiltin( IconPath( "visibilityon" ) ); // VisibilityOn
		public static Texture2D vumetertexturehorizontal          => Icon.GetOrLoadFromBuiltin( IconPath( "vumetertexturehorizontal" ) ); // VUMeterTextureHorizontal
		public static Texture2D vumetertexturevertical            => Icon.GetOrLoadFromBuiltin( IconPath( "vumetertexturevertical" ) ); // VUMeterTextureVertical
		public static Texture2D waitspin00                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin00" ) ); // WaitSpin00
		public static Texture2D waitspin01                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin01" ) ); // WaitSpin01
		public static Texture2D waitspin02                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin02" ) ); // WaitSpin02
		public static Texture2D waitspin03                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin03" ) ); // WaitSpin03
		public static Texture2D waitspin04                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin04" ) ); // WaitSpin04
		public static Texture2D waitspin05                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin05" ) ); // WaitSpin05
		public static Texture2D waitspin06                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin06" ) ); // WaitSpin06
		public static Texture2D waitspin07                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin07" ) ); // WaitSpin07
		public static Texture2D waitspin08                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin08" ) ); // WaitSpin08
		public static Texture2D waitspin09                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin09" ) ); // WaitSpin09
		public static Texture2D waitspin10                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin10" ) ); // WaitSpin10
		public static Texture2D waitspin11                        => Icon.GetOrLoadFromBuiltin( IconPath( "waitspin11" ) ); // WaitSpin11
		public static Texture2D welcomescreen_assetstorelogo      => Icon.GetOrLoadFromBuiltin( IconPath( "welcomescreen.assetstorelogo" ) ); // WelcomeScreen.AssetStoreLogo
		public static Texture2D winbtn_graph                      => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_graph" ) ); // winbtn_graph
		public static Texture2D winbtn_graph_close_h              => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_graph_close_h" ) ); // winbtn_graph_close_h
		public static Texture2D winbtn_graph_max_h                => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_graph_max_h" ) ); // winbtn_graph_max_h
		public static Texture2D winbtn_graph_min_h                => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_graph_min_h" ) ); // winbtn_graph_min_h
		public static Texture2D winbtn_mac_close                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_close" ) ); // winbtn_mac_close
		public static Texture2D winbtn_mac_close_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_close@2x" ) ); // winbtn_mac_close@2x
		public static Texture2D winbtn_mac_close_a                => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_close_a" ) ); // winbtn_mac_close_a
		public static Texture2D winbtn_mac_close_a_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_close_a@2x" ) ); // winbtn_mac_close_a@2x
		public static Texture2D winbtn_mac_close_h                => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_close_h" ) ); // winbtn_mac_close_h
		public static Texture2D winbtn_mac_close_h_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_close_h@2x" ) ); // winbtn_mac_close_h@2x
		public static Texture2D winbtn_mac_inact                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_inact" ) ); // winbtn_mac_inact
		public static Texture2D winbtn_mac_max                    => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_max" ) ); // winbtn_mac_max
		public static Texture2D winbtn_mac_max_2x                 => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_max@2x" ) ); // winbtn_mac_max@2x
		public static Texture2D winbtn_mac_max_a                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_max_a" ) ); // winbtn_mac_max_a
		public static Texture2D winbtn_mac_max_a_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_max_a@2x" ) ); // winbtn_mac_max_a@2x
		public static Texture2D winbtn_mac_max_h                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_max_h" ) ); // winbtn_mac_max_h
		public static Texture2D winbtn_mac_max_h_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_max_h@2x" ) ); // winbtn_mac_max_h@2x
		public static Texture2D winbtn_mac_min                    => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_min" ) ); // winbtn_mac_min
		public static Texture2D winbtn_mac_min_2x                 => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_min@2x" ) ); // winbtn_mac_min@2x
		public static Texture2D winbtn_mac_min_a                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_min_a" ) ); // winbtn_mac_min_a
		public static Texture2D winbtn_mac_min_a_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_min_a@2x" ) ); // winbtn_mac_min_a@2x
		public static Texture2D winbtn_mac_min_h                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_min_h" ) ); // winbtn_mac_min_h
		public static Texture2D winbtn_mac_min_h_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_min_h@2x" ) ); // winbtn_mac_min_h@2x
		public static Texture2D winbtn_win_close                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_close" ) ); // winbtn_win_close
		public static Texture2D winbtn_win_close_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_close@2x" ) ); // winbtn_win_close@2x
		public static Texture2D winbtn_win_close_a                => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_close_a" ) ); // winbtn_win_close_a
		public static Texture2D winbtn_win_close_a_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_close_a@2x" ) ); // winbtn_win_close_a@2x
		public static Texture2D winbtn_win_close_h                => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_close_h" ) ); // winbtn_win_close_h
		public static Texture2D winbtn_win_close_h_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_close_h@2x" ) ); // winbtn_win_close_h@2x
		public static Texture2D winbtn_win_max                    => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_max" ) ); // winbtn_win_max
		public static Texture2D winbtn_win_max_2x                 => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_max@2x" ) ); // winbtn_win_max@2x
		public static Texture2D winbtn_win_max_a                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_max_a" ) ); // winbtn_win_max_a
		public static Texture2D winbtn_win_max_a_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_max_a@2x" ) ); // winbtn_win_max_a@2x
		public static Texture2D winbtn_win_max_h                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_max_h" ) ); // winbtn_win_max_h
		public static Texture2D winbtn_win_max_h_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_max_h@2x" ) ); // winbtn_win_max_h@2x
		public static Texture2D winbtn_win_min                    => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_min" ) ); // winbtn_win_min
		public static Texture2D winbtn_win_min_a                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_min_a" ) ); // winbtn_win_min_a
		public static Texture2D winbtn_win_min_h                  => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_min_h" ) ); // winbtn_win_min_h
		public static Texture2D winbtn_win_rest                   => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_rest" ) ); // winbtn_win_rest
		public static Texture2D winbtn_win_rest_a                 => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_rest_a" ) ); // winbtn_win_rest_a
		public static Texture2D winbtn_win_rest_h                 => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_rest_h" ) ); // winbtn_win_rest_h
		public static Texture2D winbtn_win_restore                => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_restore" ) ); // winbtn_win_restore
		public static Texture2D winbtn_win_restore_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_restore@2x" ) ); // winbtn_win_restore@2x
		public static Texture2D winbtn_win_restore_a              => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_restore_a" ) ); // winbtn_win_restore_a
		public static Texture2D winbtn_win_restore_a_2x           => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_restore_a@2x" ) ); // winbtn_win_restore_a@2x
		public static Texture2D winbtn_win_restore_h              => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_restore_h" ) ); // winbtn_win_restore_h
		public static Texture2D winbtn_win_restore_h_2x           => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_win_restore_h@2x" ) ); // winbtn_win_restore_h@2x

		// lightskin only
		public static Texture2D _help                             => Icon.GetOrLoadFromBuiltin( IconPath( "_help" ) );
		public static Texture2D animationdopesheetkeyframe        => Icon.GetOrLoadFromBuiltin( IconPath( "animationdopesheetkeyframe" ) );
		public static Texture2D avatarcontroller_layer            => Icon.GetOrLoadFromBuiltin( IconPath( "avatarcontroller.layer" ) );
		public static Texture2D avatarcontroller_layerhover       => Icon.GetOrLoadFromBuiltin( IconPath( "avatarcontroller.layerhover" ) );
		public static Texture2D avatarcontroller_layerselected    => Icon.GetOrLoadFromBuiltin( IconPath( "avatarcontroller.layerselected" ) );
		public static Texture2D blendkey                          => Icon.GetOrLoadFromBuiltin( IconPath( "blendkey" ) );
		public static Texture2D blendkeyoverlay                   => Icon.GetOrLoadFromBuiltin( IconPath( "blendkeyoverlay" ) );
		public static Texture2D blendkeyselected                  => Icon.GetOrLoadFromBuiltin( IconPath( "blendkeyselected" ) );
		public static Texture2D blendsampler                      => Icon.GetOrLoadFromBuiltin( IconPath( "blendsampler" ) );
		public static Texture2D buildsettings_editor              => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.editor" ) );
		public static Texture2D buildsettings_editor_small        => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.editor.small" ) );
		public static Texture2D buildsettings_facebook            => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.facebook" ) );
		public static Texture2D buildsettings_facebook_small      => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.facebook.small" ) );
		public static Texture2D buildsettings_metro               => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.metro" ) );
		public static Texture2D buildsettings_metro_small         => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.metro.small" ) );
		public static Texture2D buildsettings_n3ds                => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.n3ds" ) );
		public static Texture2D buildsettings_n3ds_small          => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.n3ds.small" ) );
		public static Texture2D buildsettings_psm                 => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.psm" ) );
		public static Texture2D buildsettings_psm_small           => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.psm.small" ) );
		public static Texture2D buildsettings_standalonebroadcom_small  => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.standalonebroadcom.small" ) );
		public static Texture2D buildsettings_standalonegles20emu_small  => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.standalonegles20emu.small" ) );
		public static Texture2D buildsettings_standaloneglesemu   => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.standaloneglesemu" ) );
		public static Texture2D buildsettings_standaloneglesemu_small  => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.standaloneglesemu.small" ) );
		public static Texture2D buildsettings_switch              => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.switch" ) );
		public static Texture2D buildsettings_switch_small        => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.switch.small" ) );
		public static Texture2D buildsettings_wp8                 => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.wp8" ) );
		public static Texture2D buildsettings_wp8_small           => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.wp8.small" ) );
		public static Texture2D buildsettings_xiaomi              => Icon.GetOrLoadFromBuiltin( IconPath( "buildsettings.xiaomi" ) );
		public static Texture2D camera_gizmo                      => Icon.GetOrLoadFromBuiltin( IconPath( "camera gizmo" ) );
		public static Texture2D clipboard                         => Icon.GetOrLoadFromBuiltin( IconPath( "clipboard" ) );
		public static Texture2D clothinspector_painttool          => Icon.GetOrLoadFromBuiltin( IconPath( "clothinspector.painttool" ) );
		public static Texture2D clothinspector_paintvalue         => Icon.GetOrLoadFromBuiltin( IconPath( "clothinspector.paintvalue" ) );
		public static Texture2D clothinspector_selecttool         => Icon.GetOrLoadFromBuiltin( IconPath( "clothinspector.selecttool" ) );
		public static Texture2D clothinspector_settingstool       => Icon.GetOrLoadFromBuiltin( IconPath( "clothinspector.settingstool" ) );
		public static Texture2D clothinspector_viewvalue          => Icon.GetOrLoadFromBuiltin( IconPath( "clothinspector.viewvalue" ) );
		public static Texture2D collab_build                      => Icon.GetOrLoadFromBuiltin( IconPath( "collab.build" ) );
		public static Texture2D collab_buildfailed                => Icon.GetOrLoadFromBuiltin( IconPath( "collab.buildfailed" ) );
		public static Texture2D collab_buildsucceeded             => Icon.GetOrLoadFromBuiltin( IconPath( "collab.buildsucceeded" ) );
		public static Texture2D collab_nointernet                 => Icon.GetOrLoadFromBuiltin( IconPath( "collab.nointernet" ) );
		public static Texture2D collab                            => Icon.GetOrLoadFromBuiltin( IconPath( "collab" ) );
		public static Texture2D collab_warning                    => Icon.GetOrLoadFromBuiltin( IconPath( "collab.warning" ) );
		public static Texture2D collabconflict                    => Icon.GetOrLoadFromBuiltin( IconPath( "collabconflict" ) );
		public static Texture2D collaberror                       => Icon.GetOrLoadFromBuiltin( IconPath( "collaberror" ) );
		public static Texture2D collabnew                         => Icon.GetOrLoadFromBuiltin( IconPath( "collabnew" ) );
		public static Texture2D collaboffline                     => Icon.GetOrLoadFromBuiltin( IconPath( "collaboffline" ) );
		public static Texture2D collabprogress                    => Icon.GetOrLoadFromBuiltin( IconPath( "collabprogress" ) );
		public static Texture2D collabpull                        => Icon.GetOrLoadFromBuiltin( IconPath( "collabpull" ) );
		public static Texture2D collabpush                        => Icon.GetOrLoadFromBuiltin( IconPath( "collabpush" ) );
		public static Texture2D colorpicker_colorcycle            => Icon.GetOrLoadFromBuiltin( IconPath( "colorpicker.colorcycle" ) );
		public static Texture2D colorpicker_slidercycle           => Icon.GetOrLoadFromBuiltin( IconPath( "colorpicker.slidercycle" ) );
		public static Texture2D console_erroricon_inactive_sml    => Icon.GetOrLoadFromBuiltin( IconPath( "console.erroricon.inactive.sml" ) );
		public static Texture2D console_warnicon_inactive_sml     => Icon.GetOrLoadFromBuiltin( IconPath( "console.warnicon.inactive.sml" ) );
		public static Texture2D grid_boxtool                      => Icon.GetOrLoadFromBuiltin( IconPath( "grid.boxtool" ) );
		public static Texture2D grid_default                      => Icon.GetOrLoadFromBuiltin( IconPath( "grid.default" ) );
		public static Texture2D grid_erasertool                   => Icon.GetOrLoadFromBuiltin( IconPath( "grid.erasertool" ) );
		public static Texture2D grid_filltool                     => Icon.GetOrLoadFromBuiltin( IconPath( "grid.filltool" ) );
		public static Texture2D grid_movetool                     => Icon.GetOrLoadFromBuiltin( IconPath( "grid.movetool" ) );
		public static Texture2D grid_painttool                    => Icon.GetOrLoadFromBuiltin( IconPath( "grid.painttool" ) );
		public static Texture2D grid_pickingtool                  => Icon.GetOrLoadFromBuiltin( IconPath( "grid.pickingtool" ) );
		public static Texture2D grid_selecttool                   => Icon.GetOrLoadFromBuiltin( IconPath( "grid.selecttool" ) );
		public static Texture2D knobcshape                        => Icon.GetOrLoadFromBuiltin( IconPath( "knobcshape" ) );
		public static Texture2D knobcshapemini                    => Icon.GetOrLoadFromBuiltin( IconPath( "knobcshapemini" ) );
		public static Texture2D lightmapping                      => Icon.GetOrLoadFromBuiltin( IconPath( "lightmapping" ) );
		public static Texture2D lockicon_on                       => Icon.GetOrLoadFromBuiltin( IconPath( "lockicon-on" ) );
		public static Texture2D lockicon                          => Icon.GetOrLoadFromBuiltin( IconPath( "lockicon" ) );
		public static Texture2D lookdevcenterlightl_2x            => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevcenterlightl@2x" ) );
		public static Texture2D lookdeveyedrop                    => Icon.GetOrLoadFromBuiltin( IconPath( "lookdeveyedrop" ) );
		public static Texture2D lookdevlight                      => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevlight" ) );
		public static Texture2D lookdevlight_2x                   => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevlight@2x" ) );
		public static Texture2D lookdevshadowframe                => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevshadowframe" ) );
		public static Texture2D lookdevshadowframe_2x             => Icon.GetOrLoadFromBuiltin( IconPath( "lookdevshadowframe@2x" ) );
		public static Texture2D loop                              => Icon.GetOrLoadFromBuiltin( IconPath( "loop" ) );
		public static Texture2D p4_blueleftparenthesis            => Icon.GetOrLoadFromBuiltin( IconPath( "p4_blueleftparenthesis" ) );
		public static Texture2D p4_bluerightparenthesis           => Icon.GetOrLoadFromBuiltin( IconPath( "p4_bluerightparenthesis" ) );
		public static Texture2D p4_redleftparenthesis             => Icon.GetOrLoadFromBuiltin( IconPath( "p4_redleftparenthesis" ) );
		public static Texture2D p4_redrightparenthesis            => Icon.GetOrLoadFromBuiltin( IconPath( "p4_redrightparenthesis" ) );
		public static Texture2D p4_updating                       => Icon.GetOrLoadFromBuiltin( IconPath( "p4_updating" ) );
		public static Texture2D packagebadgedelete                => Icon.GetOrLoadFromBuiltin( IconPath( "packagebadgedelete" ) );
		public static Texture2D packagebadgenew                   => Icon.GetOrLoadFromBuiltin( IconPath( "packagebadgenew" ) );
		public static Texture2D playspeed                         => Icon.GetOrLoadFromBuiltin( IconPath( "playspeed" ) );
		public static Texture2D prematquad                        => Icon.GetOrLoadFromBuiltin( IconPath( "prematquad" ) );
		public static Texture2D pretexturearrayfirstslice         => Icon.GetOrLoadFromBuiltin( IconPath( "pretexturearrayfirstslice" ) );
		public static Texture2D pretexturearraylastslice          => Icon.GetOrLoadFromBuiltin( IconPath( "pretexturearraylastslice" ) );
		public static Texture2D profiler_globalillumination       => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.globalillumination" ) );
		public static Texture2D profiler_instrumentation          => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.instrumentation" ) );
		public static Texture2D profiler_networkmessages          => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.networkmessages" ) );
		public static Texture2D profiler_networkoperations        => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.networkoperations" ) );
		public static Texture2D profiler_physics2d                => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.physics2d" ) );
		public static Texture2D profiler_ui                       => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.ui" ) );
		public static Texture2D profiler_uidetails                => Icon.GetOrLoadFromBuiltin( IconPath( "profiler.uidetails" ) );
		public static Texture2D saveactive                        => Icon.GetOrLoadFromBuiltin( IconPath( "saveactive" ) );
		public static Texture2D savefromplay                      => Icon.GetOrLoadFromBuiltin( IconPath( "savefromplay" ) );
		public static Texture2D savepassive                       => Icon.GetOrLoadFromBuiltin( IconPath( "savepassive" ) );
		public static Texture2D sceneloadin                       => Icon.GetOrLoadFromBuiltin( IconPath( "sceneloadin" ) );
		public static Texture2D sceneloadout                      => Icon.GetOrLoadFromBuiltin( IconPath( "sceneloadout" ) );
		public static Texture2D scenesave                         => Icon.GetOrLoadFromBuiltin( IconPath( "scenesave" ) );
		public static Texture2D scenesavegrey                     => Icon.GetOrLoadFromBuiltin( IconPath( "scenesavegrey" ) );
		public static Texture2D socialnetworks_udnlogo            => Icon.GetOrLoadFromBuiltin( IconPath( "socialnetworks.udnlogo" ) );
		public static Texture2D softlockinline                    => Icon.GetOrLoadFromBuiltin( IconPath( "softlockinline" ) );
		public static Texture2D statemachineeditor_arrowtip       => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.arrowtip" ) );
		public static Texture2D statemachineeditor_arrowtipselected  => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.arrowtipselected" ) );
		public static Texture2D statemachineeditor_background     => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.background" ) );
		public static Texture2D statemachineeditor_state          => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.state" ) );
		public static Texture2D statemachineeditor_statehover     => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.statehover" ) );
		public static Texture2D statemachineeditor_stateselected  => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.stateselected" ) );
		public static Texture2D statemachineeditor_statesub       => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.statesub" ) );
		public static Texture2D statemachineeditor_statesubhover  => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.statesubhover" ) );
		public static Texture2D statemachineeditor_statesubselected  => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.statesubselected" ) );
		public static Texture2D statemachineeditor_upbutton       => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.upbutton" ) );
		public static Texture2D statemachineeditor_upbuttonhover  => Icon.GetOrLoadFromBuiltin( IconPath( "statemachineeditor.upbuttonhover" ) );
		public static Texture2D sticky_arrow                      => Icon.GetOrLoadFromBuiltin( IconPath( "sticky_arrow" ) );
		public static Texture2D sticky_p4                         => Icon.GetOrLoadFromBuiltin( IconPath( "sticky_p4" ) );
		public static Texture2D sticky_skin                       => Icon.GetOrLoadFromBuiltin( IconPath( "sticky_skin" ) );
		public static Texture2D sv_icon_dot0_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot0_sml" ) );
		public static Texture2D sv_icon_dot10_sml                 => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot10_sml" ) );
		public static Texture2D sv_icon_dot11_sml                 => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot11_sml" ) );
		public static Texture2D sv_icon_dot12_sml                 => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot12_sml" ) );
		public static Texture2D sv_icon_dot13_sml                 => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot13_sml" ) );
		public static Texture2D sv_icon_dot14_sml                 => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot14_sml" ) );
		public static Texture2D sv_icon_dot15_sml                 => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot15_sml" ) );
		public static Texture2D sv_icon_dot1_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot1_sml" ) );
		public static Texture2D sv_icon_dot2_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot2_sml" ) );
		public static Texture2D sv_icon_dot3_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot3_sml" ) );
		public static Texture2D sv_icon_dot4_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot4_sml" ) );
		public static Texture2D sv_icon_dot5_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot5_sml" ) );
		public static Texture2D sv_icon_dot6_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot6_sml" ) );
		public static Texture2D sv_icon_dot7_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot7_sml" ) );
		public static Texture2D sv_icon_dot8_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot8_sml" ) );
		public static Texture2D sv_icon_dot9_sml                  => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_dot9_sml" ) );
		public static Texture2D sv_icon_name0                     => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_name0" ) );
		public static Texture2D sv_icon_name1                     => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_name1" ) );
		public static Texture2D sv_icon_name2                     => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_name2" ) );
		public static Texture2D sv_icon_name3                     => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_name3" ) );
		public static Texture2D sv_icon_name4                     => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_name4" ) );
		public static Texture2D sv_icon_name5                     => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_name5" ) );
		public static Texture2D sv_icon_name6                     => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_name6" ) );
		public static Texture2D sv_icon_name7                     => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_name7" ) );
		public static Texture2D sv_icon_none                      => Icon.GetOrLoadFromBuiltin( IconPath( "sv_icon_none" ) );
		public static Texture2D sv_label_0                        => Icon.GetOrLoadFromBuiltin( IconPath( "sv_label_0" ) );
		public static Texture2D sv_label_1                        => Icon.GetOrLoadFromBuiltin( IconPath( "sv_label_1" ) );
		public static Texture2D sv_label_2                        => Icon.GetOrLoadFromBuiltin( IconPath( "sv_label_2" ) );
		public static Texture2D sv_label_3                        => Icon.GetOrLoadFromBuiltin( IconPath( "sv_label_3" ) );
		public static Texture2D sv_label_4                        => Icon.GetOrLoadFromBuiltin( IconPath( "sv_label_4" ) );
		public static Texture2D sv_label_5                        => Icon.GetOrLoadFromBuiltin( IconPath( "sv_label_5" ) );
		public static Texture2D sv_label_6                        => Icon.GetOrLoadFromBuiltin( IconPath( "sv_label_6" ) );
		public static Texture2D sv_label_7                        => Icon.GetOrLoadFromBuiltin( IconPath( "sv_label_7" ) );
		public static Texture2D terraininspector_terraintooladd   => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintooladd" ) );
		public static Texture2D terraininspector_terraintoollower  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoollower" ) );
		public static Texture2D terraininspector_terraintoolsculpt_on  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsculpt on" ) );
		public static Texture2D terraininspector_terraintoolsculpt  => Icon.GetOrLoadFromBuiltin( IconPath( "terraininspector.terraintoolsculpt" ) );
		public static Texture2D testfailed                        => Icon.GetOrLoadFromBuiltin( IconPath( "testfailed" ) );
		public static Texture2D testignored                       => Icon.GetOrLoadFromBuiltin( IconPath( "testignored" ) );
		public static Texture2D testinconclusive                  => Icon.GetOrLoadFromBuiltin( IconPath( "testinconclusive" ) );
		public static Texture2D testnormal                        => Icon.GetOrLoadFromBuiltin( IconPath( "testnormal" ) );
		public static Texture2D testpassed                        => Icon.GetOrLoadFromBuiltin( IconPath( "testpassed" ) );
		public static Texture2D teststopwatch                     => Icon.GetOrLoadFromBuiltin( IconPath( "teststopwatch" ) );
		public static Texture2D timelineclipbg                    => Icon.GetOrLoadFromBuiltin( IconPath( "timelineclipbg" ) );
		public static Texture2D timelineclipfg                    => Icon.GetOrLoadFromBuiltin( IconPath( "timelineclipfg" ) );
		public static Texture2D unityeditor_graphs_animatorcontrollertool  => Icon.GetOrLoadFromBuiltin( IconPath( "unityeditor.graphs.animatorcontrollertool" ) );
		public static Texture2D unitylogolarge                    => Icon.GetOrLoadFromBuiltin( IconPath( "unitylogolarge" ) );
		public static Texture2D uparrow                           => Icon.GetOrLoadFromBuiltin( IconPath( "uparrow" ) );
		public static Texture2D vcs_add                           => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_add" ) );
		public static Texture2D vcs_branch                        => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_branch" ) );
		public static Texture2D vcs_change                        => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_change" ) );
		public static Texture2D vcs_check                         => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_check" ) );
		public static Texture2D vcs_delete                        => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_delete" ) );
		public static Texture2D vcs_document                      => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_document" ) );
		public static Texture2D vcs_edit                          => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_edit" ) );
		public static Texture2D vcs_incoming                      => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_incoming" ) );
		public static Texture2D vcs_integrate                     => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_integrate" ) );
		public static Texture2D vcs_local                         => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_local" ) );
		public static Texture2D vcs_lock                          => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_lock" ) );
		public static Texture2D vcs_refresh                       => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_refresh" ) );
		public static Texture2D vcs_sync                          => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_sync" ) );
		public static Texture2D vcs_unresolved                    => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_unresolved" ) );
		public static Texture2D vcs_update                        => Icon.GetOrLoadFromBuiltin( IconPath( "vcs_update" ) );
		public static Texture2D visualeffect_gizmo                => Icon.GetOrLoadFromBuiltin( IconPath( "visualeffect gizmo" ) );
		public static Texture2D winbtn_mac_inact_2x               => Icon.GetOrLoadFromBuiltin( IconPath( "winbtn_mac_inact@2x" ) );
	}
}

#endif

