// Generated by Assets/Hananoki/SharedModule/Localize/ja-JP.csv
namespace Hananoki.SharedModule {
	public static class L {
		public static string Tr( string s ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), s );
		}
		public static string[] Tr( string[] ss ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), ss );
		}
	}
	public static class S {
		public static string _OK => L.Tr( "OK" );
		public static string _Cancel => L.Tr( "Cancel" );
		public static string _Apply => L.Tr( "Apply" );
		public static string _Revert => L.Tr( "Revert" );
		public static string _Confirm => L.Tr( "Confirm" );
		public static string _Continue => L.Tr( "Continue" );
		public static string _Language => L.Tr( "Language" );
		public static string _Experimental => L.Tr( "Experimental" );
		public static string _Directory => L.Tr( "Directory" );
		public static string _Preferences => L.Tr( "Preferences" );
		public static string _ProjectSettings => L.Tr( "Project Settings" );
		public static string _Settings_Editor_ => L.Tr( "Settings (Editor)" );
		public static string _Settings_Project_ => L.Tr( "Settings (Project)" );
		public static string _Add => L.Tr( "Add" );
		public static string _Replace => L.Tr( "Replace" );
		public static string _Clear => L.Tr( "Clear" );
		public static string _Cut => L.Tr( "Cut" );
		public static string _Copy => L.Tr( "Copy" );
		public static string _Paste => L.Tr( "Paste" );
		public static string _Duplicate => L.Tr( "Duplicate" );
		public static string _Delete => L.Tr( "Delete" );
		public static string _Rename => L.Tr( "Rename" );
		public static string _Install => L.Tr( "Install" );
		public static string _Uninstall => L.Tr( "Uninstall" );
		public static string _Copytoclipboard => L.Tr( "Copy to clipboard" );
		public static string _Pleaseselectadirectory => L.Tr( "Please select a directory" );
		public static string _IsitOK_ => L.Tr( "Is it OK?" );
		public static string _Deprecated => L.Tr( "Deprecated" );
		public static string _Warning => L.Tr( "Warning" );
		public static string _Info => L.Tr( "Info" );
		public static string _Enable => L.Tr( "Enable" );
		public static string _Rowcolor => L.Tr( "Row color" );
		public static string _ContextMenuWithIconClick => L.Tr( "Context Menu With Icon Click" );
		public static string _Changecolorforeachrow => L.Tr( "Change color for each row" );
		public static string _OpenInNewInspector => L.Tr( "Open In New Inspector" );
		public static string _BackColor => L.Tr( "Back Color" );
		public static string _TextColor => L.Tr( "Text Color" );
		public static string _Font => L.Tr( "Font" );
		public static string _FontStyle => L.Tr( "Font Style" );
		public static string _Input => L.Tr( "Input" );
		public static string _TagsandLayers => L.Tr( "Tags and Layers" );
		public static string _Audio => L.Tr( "Audio" );
		public static string _Time => L.Tr( "Time" );
		public static string _Player => L.Tr( "Player" );
		public static string _Physics => L.Tr( "Physics" );
		public static string _Physics2D => L.Tr( "Physics 2D" );
		public static string _Quality => L.Tr( "Quality" );
		public static string _Graphics => L.Tr( "Graphics" );
		public static string _Network => L.Tr( "Network" );
		public static string _Editor => L.Tr( "Editor" );
		public static string _ScriptExecutionOrder => L.Tr( "Script Execution Order" );
		public static string _OpenOutputFolder => L.Tr( "Open Output Folder" );
		public static string _ReloadScene => L.Tr( "Reload Scene" );
		public static string _Therearenoscenesregisteredinthebuildsettings => L.Tr( "There are no scenes registered in the build settings" );
		public static string _Filenotfound => L.Tr( "File not found" );
		public static string _RequiresSwitchActiveBuildTarget => L.Tr( "Requires SwitchActiveBuildTarget" );
		public static string _ProjectSettingsProvider => L.Tr( "Project Settings Provider" );
		public static string _GameViewScreenShot => L.Tr( "GameView ScreenShot" );
		public static string _OpenAssetStore => L.Tr( "Open Asset Store" );
		public static string _OpenCSharpProject => L.Tr( "Open C# Project" );
		public static string _OpenSettings => L.Tr( "Open Settings" );
		public static string _OpenBuildSettings => L.Tr( "Open Build Settings" );
		public static string _EnablePingObject => L.Tr( "Enable Ping Object" );
		public static string _RecordObjectCount => L.Tr( "Record Object Count" );
		public static string _ShowinExplorer => L.Tr( "Show in Explorer" );
		public static string _SelectAsset => L.Tr( "Select Asset" );
		public static string _EditScript => L.Tr( "Edit Script" );
		public static string _VersionTextColor => L.Tr( "Version Text Color" );
		public static string _VersionBackColor => L.Tr( "Version Back Color" );
		public static string _Animation => L.Tr( "Animation" );
		public static string _Animator => L.Tr( "Animator" );
		public static string _Timeline => L.Tr( "Timeline" );
		public static string _Console => L.Tr( "Console" );
		public static string _Profiler => L.Tr( "Profiler" );
	}
}
