// Generated by Assets/Hananoki/SharedModule/Localize/en-US.csv

namespace Hananoki.SharedModule {
	public static class L {
		public static string Tr( int n ) {
			try {
				return EditorLocalize.GetPakage( Package.name ).m_Strings[ n ];
			}
			catch( System.Exception ) {
			}
			return string.Empty;
		}
	}
	public static class S {
		public static string _OK => L.Tr( 0 );
		public static string _Cancel => L.Tr( 1 );
		public static string _Yes => L.Tr( 2 );
		public static string _No => L.Tr( 3 );
		public static string _Apply => L.Tr( 4 );
		public static string _Revert => L.Tr( 5 );
		public static string _Confirm => L.Tr( 6 );
		public static string _Continue => L.Tr( 7 );
		public static string _Language => L.Tr( 8 );
		public static string _Experimental => L.Tr( 9 );
		public static string _Directory => L.Tr( 10 );
		public static string _Load => L.Tr( 11 );
		public static string _Save => L.Tr( 12 );
		public static string _Edit => L.Tr( 13 );
		public static string _Preferences => L.Tr( 14 );
		public static string _ProjectSettings => L.Tr( 15 );
		public static string _Settings_Editor_ => L.Tr( 16 );
		public static string _Settings_Project_ => L.Tr( 17 );
		public static string _Settings => L.Tr( 18 );
		public static string _General => L.Tr( 19 );
		public static string _Add => L.Tr( 20 );
		public static string _Replace => L.Tr( 21 );
		public static string _Clear => L.Tr( 22 );
		public static string _Cut => L.Tr( 23 );
		public static string _Copy => L.Tr( 24 );
		public static string _Paste => L.Tr( 25 );
		public static string _Duplicate => L.Tr( 26 );
		public static string _Delete => L.Tr( 27 );
		public static string _Rename => L.Tr( 28 );
		public static string _Install => L.Tr( 29 );
		public static string _Uninstall => L.Tr( 30 );
		public static string _Copytoclipboard => L.Tr( 31 );
		public static string _Pleaseselectadirectory => L.Tr( 32 );
		public static string _IsitOK_ => L.Tr( 33 );
		public static string _Start => L.Tr( 34 );
		public static string _Stop => L.Tr( 35 );
		public static string _Deprecated => L.Tr( 36 );
		public static string _Warning => L.Tr( 37 );
		public static string _Info => L.Tr( 38 );
		public static string _Enable => L.Tr( 39 );
		public static string _Rowcolor => L.Tr( 40 );
		public static string _ContextMenuWithIconClick => L.Tr( 41 );
		public static string _Changecolorforeachrow => L.Tr( 42 );
		public static string _OpenInNewInspector => L.Tr( 43 );
		public static string _BackColor => L.Tr( 44 );
		public static string _TextColor => L.Tr( 45 );
		public static string _Font => L.Tr( 46 );
		public static string _FontStyle => L.Tr( 47 );
		public static string _Tools => L.Tr( 48 );
		public static string _Analysis => L.Tr( 49 );
		public static string _Input => L.Tr( 50 );
		public static string _TagsandLayers => L.Tr( 51 );
		public static string _Audio => L.Tr( 52 );
		public static string _Time => L.Tr( 53 );
		public static string _Player => L.Tr( 54 );
		public static string _Physics => L.Tr( 55 );
		public static string _Physics2D => L.Tr( 56 );
		public static string _Quality => L.Tr( 57 );
		public static string _Graphics => L.Tr( 58 );
		public static string _Network => L.Tr( 59 );
		public static string _Editor => L.Tr( 60 );
		public static string _ScriptExecutionOrder => L.Tr( 61 );
		public static string _OpenOutputFolder => L.Tr( 62 );
		public static string _ReloadScene => L.Tr( 63 );
		public static string _Therearenoscenesregisteredinthebuildsettings => L.Tr( 64 );
		public static string _Filenotfound => L.Tr( 65 );
		public static string _RequiresSwitchActiveBuildTarget => L.Tr( 66 );
		public static string _ProjectSettingsProvider => L.Tr( 67 );
		public static string _GameViewScreenShot => L.Tr( 68 );
		public static string _OpenAssetStore => L.Tr( 69 );
		public static string _OpenCSharpProject => L.Tr( 70 );
		public static string _OpenSettings => L.Tr( 71 );
		public static string _OpenBuildSettings => L.Tr( 72 );
		public static string _EnablePingObject => L.Tr( 73 );
		public static string _RecordObjectCount => L.Tr( 74 );
		public static string _ShowinExplorer => L.Tr( 75 );
		public static string _SelectAsset => L.Tr( 76 );
		public static string _EditScript => L.Tr( 77 );
		public static string _VersionTextColor => L.Tr( 78 );
		public static string _VersionBackColor => L.Tr( 79 );
		public static string _Animation => L.Tr( 80 );
		public static string _Animator => L.Tr( 81 );
		public static string _Timeline => L.Tr( 82 );
		public static string _Console => L.Tr( 83 );
		public static string _Profiler => L.Tr( 84 );
		public static string _MakeJSONPrettyPrint => L.Tr( 85 );
		public static string _WheretosaveProjectsettings => L.Tr( 86 );
		public static string _Makepackagesettings => L.Tr( 87 );
		public static string _UseProjectSettings => L.Tr( 88 );
		public static string _FolderSetting => L.Tr( 89 );
		public static string _Interface => L.Tr( 90 );
		public static string _UtilityWindowMode => L.Tr( 91 );
		public static string _ReturnToDefault => L.Tr( 92 );
		public static string _Downloading => L.Tr( 93 );
		public static string _Filedoesnotexist => L.Tr( 94 );
		public static string _Fileexists => L.Tr( 95 );
		public static string _Updatetothelateststatus => L.Tr( 96 );
		public static string _Templatefilenotfound => L.Tr( 97 );
		public static string _ScriptTemplates => L.Tr( 98 );
	}

#if UNITY_EDITOR
  [EditorLocalizeClass]
  public class LocalizeEvent {
    [EditorLocalizeMethod]
    public static void Changed() {
			EditorLocalize.Load( Package.name, "95cedfc7731853946b0b3650f175d73a" );
		}
	}
#endif
}
